### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by cschol** [ianjhoffman/RigatoniModular#1]
Error in Rack log:

```
[0.036 warn src/plugin.cpp:230 loadPlugin] Could not load plugin Rigatoni: Manifest contains module RigatoniModular-ThruZero but it is not defined in plugin
```

Check mismatch between `plugin.json` and source code.

**Comment by ianjhoffman** [comment]
@cschol I think my latest commit should fix this. That said, how can I make sure I don't run into this in the future since `make install` was working fine for me locally?

**Comment by cschol** [comment]
It is impossible for that code to work. You should have seen this as well.

**Comment by cschol** [comment]
New issue:

```
[1.262 warn src/window/Svg.cpp:112 load] Failed to load SVG /home/cschol/src/Rack-2.0-Home/plugins-lin-x64/Rigatoni/res/panels/ThruZero.svg
```

The problem is that on case-sensitive filesystems, like GNU/Linux, the filename has to match the code:

![image](https://github.com/ianjhoffman/RigatoniModular/assets/624427/28bf06b0-26d5-4dab-b833-6209db4d89a2)

**Comment by ianjhoffman** [comment]
I don't know what to say other than that I wasn't having issues, but perhaps because I already had the plugin installed... I'll make sure to remove it from my user directory in the future when doing final builds before releasing a module. 

My apologies for the small issues - latest commit corrects the case on the SVG filename in `thruzero.cpp`

**Comment by cschol** [comment]
No worries. It's part of the process of releasing a module for the first time. Cross-platform development has its quirks.

**Comment by ianjhoffman** [comment]
Thanks for being understanding! I'm also in the process of adding more of a formal manual for the Thru Zero module to the `README.md` so it's easier to use

**Comment by cschol** [comment]
Fixed.
